# language this project is using
language: python
# version of the language
python:
  - "3.6"
# services for travis to use
services:
  - docker
# script for travis to run before scripts are ran
before_script: pip install docker-compose
# jobs for travis to run
jobs:
  include:
    - stage: test
      script: docker-compose run app sh -c "python manage.py test"
    - stage: lint
      script: docker-compose run app sh -c "flake8"
