# version of docker compose to use
version: "3"

services:
  # name of our service
  app:
    # build section of our service
    build:
      # set context (directory to run docker compose in, relative to host)
      context: .
    # port config
    ports:
      # port forwarding HOST:CONTAINER
      - "8000:8000"
    # volume config
    volumes:
      # map ./app on host to /app in container
      - ./app:/app
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=app
      - DB_USER=postgres
      - DB_PASS=supersecretpassword
    depends_on:
      - db
  db:
    # use postgres 10 alpine as base image
    image: postgres:10-alpine
    # environment variables
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=postgres
      - POSTGRESS_PASSWORD=supersecretpassword
