# version of docker compose to use
version: "3.8"

services:
  # name of our service
  app:
    # build section of our service
    build:
      # set context (directory to run docker compose in, relative to host)
      context: .
    # port config
    ports:
      # port forwarding HOST:CONTAINER
      - "8000:8000"
    # volume config
    volumes:
      # map ./app on host to /app in container
      - ./app:/app
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=app
      - DB_USER=postgres
      - DB_PASS=supersecretpassword
    depends_on:
      - db
  db:
    # use postgres 10 alpine as base image
    image: postgres:10-alpine
    # host
    hostname: db
    # environment variables
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=supersecretpassword
    ports:
      - "5432:5432"
